export enum UserPermission {
  userCreate = "user:CREATE",
  userRead = "user:READ",
  userDelete = "user:DELETE",
  userUpdate = "user:UPDATE",
  companyCreate = "company:CREATE",
  companyRead = "company:READ",
  companyDelete = "company:DELETE",
  companyUpdate = "company:UPDATE",
  entityRead = "entity:READ",
  entityUpdate = "entity:UPDATE",
  entityDelete = "entity:DELETE",
  entityCreate = "entity:CREATE",
  obligationRead = "obligation:READ",
  obligationUpdate = "obligation:UPDATE",
  obligationDelete = "obligation:DELETE",
  obligationCreate = "obligation:CREATE",
  assetRead = "asset:READ",
  assetUpdate = "asset:UPDATE",
  assetDelete = "asset:DELETE",
  assetCreate = "asset:CREATE",
  usersRead = "users:READ",
  usersUpdate = "users:UPDATE",
  usersDelete = "users:DELETE",
  usersCreate = "users:CREATE",
}
